package hicham.auth;
 

import java.lang.reflect.Method;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import hicham.auth.user.User;
import hicham.auth.user.UserRepository;

@Controller
@RequestMapping("/")
//@EnableWebMvc 
//@EnableAutoConfiguration
public class WelcomeController {
	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@RequestMapping("/w")
	public String welcome(ModelMap map) {
		map.put("currentDate", new Date());
		return "welcome";
	}

	@RequestMapping(value= "/add",method= RequestMethod.GET) // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam(value="t1") String name
			, @RequestParam(value="t2") String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@RequestMapping(value= "/all",method= RequestMethod.GET)
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	@RequestMapping(value= "{id}",method= RequestMethod.GET)
	public @ResponseBody User getUser(@PathVariable("id") int id) {
		// This returns a JSON or XML with the users
		return userRepository.findOne(id);
	}
	
	@RequestMapping(value="/hello", method= RequestMethod.POST)
	public String hello(HttpServletRequest request, Model model) {
		User user= new User();
		user.setEmail("");
		model.addAttribute("message", null);
		return "hello";
	}
	
}